### ISSUE TITLE
EZCOO MX44-HAS2 4x4 HDMI Matrix

### ISSUE THREAD

**Issue by jbubik** [bitfocus/companion-module-ezcoo-matrix#1]
I would like to donate complete Companion module for EZCOO 4x4 HDMI Matrix.
Product: [MX44-HAS2](https://www.easycoolav.com/products/4k60-444-hdmi-matrix-4x4-dolby-vision-with-audio-breakout-ip-rs232-ir-control-hdcp22-18g-bps)
Suggested repository name: companion-module-ezcoo-matrix
I acknowledge the module is heavily based on companion-module-cyp-matrix
Initial release 1.0.0 here: [companion-module-ezcoo-matrix.zip](https://github.com/bitfocus/companion-module-requests/files/9679245/companion-module-ezcoo-matrix.zip)

**Comment by jbubik** [comment]
@josephdadams: if you create an empty repository, I will fork, commit and create PR.
The code has been tested with a real device.
Thanks
Jan

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion-module-ezcoo-matrix

**Comment by jbubik** [comment]
Greetings @josephdadams,
the code is in the repo now. I can `git clone` into `module-local-dev` and then `yarn install`.
Everything works. What are the next steps to include the module into Companion release?
Jan

**Comment by jbubik** [comment]
@krocheck , @Julusian: can you include this module into the next Companion release? Companion 2.4.0 is probably out already, so the next one? Thanks!

**Comment by Julusian** [comment]
This is updated this for 3.0 and it is included in the builds.

I have a similar 4x2 model, and have tested it against that
